=== Elijas/job-offer-scraper/jobs-data/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "iBus job",
    "description": "Currently available job @ iBus Media",
    "type": "object",
    "properties": {
        "title": {
            "description": "job title",
            "type": "string"
        },
        "location": {
            "description": "office location",
            "type": "string"
        },
        "date": {
            "description": "date",
            "type": "string"
        },
        "content": {
            "description": "job decription",
            "type": "string"
        },
        "apply_link": {
            "description": "link to apply for job",
            "type": "string"
        } 
    },
    "required": ["title", "location", "apply_link"]
}

=== Elijas/job-offer-scraper/jobs-data/jobs/0.json
{"title":"SEO content writers wanted","location":"Remote","date":"12 October 2018","content":"iBus Media - one of the world's leading companies in iGaming industry is currently looking for freelance content providers. You will be asked to write 500-700 word articles for different websites and topics.\u00a0\nWhat we\u2019re looking for is speed, dependability and high attention to detail. We need experienced writers who know how to create web articles on various topics, format them properly, and include high quality internal and external links.\n\u00a0As part of our interview process we will ask you to complete an assignment. The content produced while completing the assignment will not be used or published it's designed for us to gauge your skills and approach to tasks.\nPositions are available within the following languages:\u00a0English (content about USA sports, or Casino or Poker), Italian, German, Dutch, Swedish, Danish. \nIf you have solid writing\/editing skills, please get in touch! SEO\nknowledge is an asset. \nInterested? Don\u2019t hesitate to send your application to freelancers@discovermedia.io .\nJob Type: Freelancer\n\u00a0\nBefore applying please read\u00a0iBus Media Recruitment Privacy Notice\u00a0carefully.\u00a0\nDepartment:\nContent\n","apply_link":"https:\/\/ibusmedialimited.peoplehr.net\/Pages\/JobBoard\/Opening.aspx?v=db72d41c-e127-4267-b0eb-d6b3db319257"}

=== Elijas/job-offer-scraper/jobs-data/jobs/1.json
{"title":"Outreach Specialist","location":"Barcelona, Spain","date":"18 January 2019","content":"We at\u00a0iBus\u00a0Media\nare looking for\u00a0enthusiastic and highly\nmotivated individuals\u00a0to\u00a0fill\u00a0available\u00a0Outreach Specialist\u00a0positions\u00a0in\u00a0our\u00a0ever-expanding\u00a0Content Marketing and Outreach\u00a0Department\u00a0(CMOD).\u00a0All\u00a0Outreach Specialists\u00a0will work\u00a0directly\u00a0under the supervision of the\u00a0Outreach\u00a0Manager\u00a0to develop and implement\u00a0outreach\u00a0strategies\u00a0in order\u00a0to\u00a0scale existing content marketing and outreach efforts.\u00a0If you are looking to join a talented\u00a0team\u00a0and are looking for an\u00a0opportunity for professional growth please send us your CV and cover letter (in English)\u00a0with subject \u201cOutreach\nSpecialist\u201c.\u00a0\n\u00a0\nDuties and Responsibilities:\u00a0\nB2B Outreach\u00a0Suggest and help implement outreach strategy improvements\u00a0Outreach partner portfolio developmentEnsure content marketing quality standarts and guidelines are being implemented\u00a0\n\u00a0\nEssential\u00a0Skills:\u00a0\nB2B outreach and\/or\u00a0sales experience\u00a0English is\u00a0required. German or Italian languages are a plus.\nA passion for connecting with people and all things internet.\n\u00a0\nDesired Skills:\u00a0\nInbound marketing\n(SEO) knowledge or experience\u00a0A\u00a0good\u00a0understanding of\u00a0SEO and\nweb\u00a0positioning\u00a0metrics\u00a0Experience with web analytic software such as Google Analytics, Open site Explorer, Majestic and SEMrushContent marketing experience\u00a0\n\u00a0\u00a0\n\u00a0Before applying please read\u00a0iBus Media Recruitment Privacy Notice\u00a0carefully.\u00a0\u00a0\nDepartment:\nB2B\n","apply_link":"https:\/\/ibusmedialimited.peoplehr.net\/Pages\/JobBoard\/Opening.aspx?v=6199e30a-b244-44bf-8d5f-d04cfe0ca9c7"}

=== Elijas/job-offer-scraper/jobs-data/jobs.json
[{"title":"SEO content writers wanted","location":"Remote","date":"12 October 2018","content":"iBus Media - one of the world's leading companies in iGaming industry is currently looking for freelance content providers. You will be asked to write 500-700 word articles for different websites and topics.\u00a0\nWhat we\u2019re looking for is speed, dependability and high attention to detail. We need experienced writers who know how to create web articles on various topics, format them properly, and include high quality internal and external links.\n\u00a0As part of our interview process we will ask you to complete an assignment. The content produced while completing the assignment will not be used or published it's designed for us to gauge your skills and approach to tasks.\nPositions are available within the following languages:\u00a0English (content about USA sports, or Casino or Poker), Italian, German, Dutch, Swedish, Danish. \nIf you have solid writing\/editing skills, please get in touch! SEO\nknowledge is an asset. \nInterested? Don\u2019t hesitate to send your application to freelancers@discovermedia.io .\nJob Type: Freelancer\n\u00a0\nBefore applying please read\u00a0iBus Media Recruitment Privacy Notice\u00a0carefully.\u00a0\nDepartment:\nContent\n","apply_link":"https:\/\/ibusmedialimited.peoplehr.net\/Pages\/JobBoard\/Opening.aspx?v=db72d41c-e127-4267-b0eb-d6b3db319257"},{"title":"Outreach Specialist","location":"Barcelona, Spain","date":"18 January 2019","content":"We at\u00a0iBus\u00a0Media\nare looking for\u00a0enthusiastic and highly\nmotivated individuals\u00a0to\u00a0fill\u00a0available\u00a0Outreach Specialist\u00a0positions\u00a0in\u00a0our\u00a0ever-expanding\u00a0Content Marketing and Outreach\u00a0Department\u00a0(CMOD).\u00a0All\u00a0Outreach Specialists\u00a0will work\u00a0directly\u00a0under the supervision of the\u00a0Outreach\u00a0Manager\u00a0to develop and implement\u00a0outreach\u00a0strategies\u00a0in order\u00a0to\u00a0scale existing content marketing and outreach efforts.\u00a0If you are looking to join a talented\u00a0team\u00a0and are looking for an\u00a0opportunity for professional growth please send us your CV and cover letter (in English)\u00a0with subject \u201cOutreach\nSpecialist\u201c.\u00a0\n\u00a0\nDuties and Responsibilities:\u00a0\nB2B Outreach\u00a0Suggest and help implement outreach strategy improvements\u00a0Outreach partner portfolio developmentEnsure content marketing quality standarts and guidelines are being implemented\u00a0\n\u00a0\nEssential\u00a0Skills:\u00a0\nB2B outreach and\/or\u00a0sales experience\u00a0English is\u00a0required. German or Italian languages are a plus.\nA passion for connecting with people and all things internet.\n\u00a0\nDesired Skills:\u00a0\nInbound marketing\n(SEO) knowledge or experience\u00a0A\u00a0good\u00a0understanding of\u00a0SEO and\nweb\u00a0positioning\u00a0metrics\u00a0Experience with web analytic software such as Google Analytics, Open site Explorer, Majestic and SEMrushContent marketing experience\u00a0\n\u00a0\u00a0\n\u00a0Before applying please read\u00a0iBus Media Recruitment Privacy Notice\u00a0carefully.\u00a0\u00a0\nDepartment:\nB2B\n","apply_link":"https:\/\/ibusmedialimited.peoplehr.net\/Pages\/JobBoard\/Opening.aspx?v=6199e30a-b244-44bf-8d5f-d04cfe0ca9c7"},{"title":"Content Manager","location":"Vilnius, Lithuania","date":"04 April 2019","content":"Are you a good writer? We're currently looking for a highly creative content writer to create and outsource high quality content for our websites.\nPosition offered: Content Manager\u00a0\n\u00a0\nDuties and Responsibilities:\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Write content including features and news articles;\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Edit stories for content, grammar, voice and length;\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Assist with story fact checking;\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Plan and conceptualize editorial content;\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Compiling keyword research and analysis.\n\u00a0\nEssential Skills: \nProven experience in writing, editing, and proof reading;Ability to work under strict deadlines;\u00a0High level of creativity;Excellent communication skills (email, Skype, in-person);\u00a0 \u00a0Professional fluency in English;Optimist.\n\u00a0\nDesired Skills:\nDegree in English Philology\n\u00a0Before applying please read\u00a0iBus Media Recruitment Privacy Notice\u00a0carefully.\u00a0\u00a0\u00a0\nDepartment:\nContent\n","apply_link":"https:\/\/ibusmedialimited.peoplehr.net\/Pages\/JobBoard\/Opening.aspx?v=be984c9f-3922-42af-89e2-425b23e19782"}]

=== Elijas/job-offer-scraper/jobs-data/jobs/2.json
{"title":"Content Manager","location":"Vilnius, Lithuania","date":"04 April 2019","content":"Are you a good writer? We're currently looking for a highly creative content writer to create and outsource high quality content for our websites.\nPosition offered: Content Manager\u00a0\n\u00a0\nDuties and Responsibilities:\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Write content including features and news articles;\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Edit stories for content, grammar, voice and length;\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Assist with story fact checking;\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Plan and conceptualize editorial content;\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0Compiling keyword research and analysis.\n\u00a0\nEssential Skills: \nProven experience in writing, editing, and proof reading;Ability to work under strict deadlines;\u00a0High level of creativity;Excellent communication skills (email, Skype, in-person);\u00a0 \u00a0Professional fluency in English;Optimist.\n\u00a0\nDesired Skills:\nDegree in English Philology\n\u00a0Before applying please read\u00a0iBus Media Recruitment Privacy Notice\u00a0carefully.\u00a0\u00a0\u00a0\nDepartment:\nContent\n","apply_link":"https:\/\/ibusmedialimited.peoplehr.net\/Pages\/JobBoard\/Opening.aspx?v=be984c9f-3922-42af-89e2-425b23e19782"}
